### ISSUE TITLE
Как работает вес?

### ISSUE THREAD

**Issue by Spaider15** [yandex/mapsapi-heatmap#10]
Добрый день, есть следующая задача: есть 6 типов точек, от самой большой до самой маленькой, нужно сделать так, что бы на тепловой карте их можно было различить, не могу добиться нужного результата.

Самое близкое сейчас это то что в примере, 6 5 и 4 различаются, а дальше все идут просто зеленые
![image](https://user-images.githubusercontent.com/12617760/100589226-e1bb5080-3303-11eb-9ab7-fd3b9ed84ec1.png)

Пример: https://jsfiddle.net/28ujbc3n/6/
Подскажите пожалуйста, как им правильно выставить веса, что бы все 6 были разные? 

6 - самая красная
5 - менее красная
4 оранжевая и т.д
Спасибо!

**Comment by ch-ms** [comment]
Можно попробовать сдвинуть intensityOfMidpoint на 0.5 и равномерно распределить веса. У меня получилось как то так https://jsfiddle.net/bpuaskj4/

**Comment by Spaider15** [comment]
Спасибо, похоже это то что надо!
